use_frameworks!
platform :ios, '9.0'

target 'SocialKit_Example' do

  pod 'SocialKit', :path => '../'
  pod 'JacKit', :path => '../../JacKit'

  pod 'Eureka'

  target 'SocialKit_Tests' do
    inherit! :search_paths

  end
end
