use_frameworks!
platform :ios, '9.0'

target 'Example' do

  pod 'JacKit', :path => '../../JacKit'
  pod 'iOSKit', :path => '../../iOSKit'
  pod 'SocialKit', :path => '../'

  pod 'Eureka'

  target 'Tests' do
    inherit! :search_paths

  end
end
