use_frameworks!
platform :ios, '9.0'

target 'Demo' do

  pod 'JacKit',     :path => '../../JacKit'
  pod 'iOSKit',     :path => '../../iOSKit'
  pod 'iOSKit/MBP', :path => '../../iOSKit'
  pod 'SocialKit',  :path => '../'

  pod 'Eureka'
  pod 'Kingfisher'

  target 'Tests' do
    inherit! :search_paths

  end
end
